name: Cherry pick into v3.0.0/develop
permissions: read-all

on:
  pull_request:
    branches:
      - develop
    types: ["closed"]

jobs:
  cherry_pick_release_v3_0:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    name: Cherry pick into v3.0.0/develop
    if: ${{ github.event.pull_request.merged == true }}
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
        with:
          fetch-depth: 0
      - name: Cherry pick into v3.0.0/develop
        uses: carloscastrojumo/github-cherry-pick-action@bb0869df47c27be4ae4c7a2d93d22827aa5a0054
        with:
          branch: v3.0.0/develop
          labels: |
            cherry-pick
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}